# Generated by Django 2.2.5 on 2019-11-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censado',
            name='hora',
            field=models.IntegerField(),
        ),
    ]
